PGM
    CRTLIB LIB(QDEMO)
    CRTPF FILE(QDEMO/CUSTOMERS) RCDLEN(80) FIELDS(KEY:CHAR:8,DATA:CHAR:72) KEY(KEY)
    WRTPFM FILE(QDEMO/CUSTOMERS) KEY(C001) DATA('ALICE')
    WRTPFM FILE(QDEMO/CUSTOMERS) KEY(C002) DATA('BOB')
    CRTLF FILE(QDEMO/CUSTBYNAME) SRCFILE(QDEMO/CUSTOMERS) SELECT(ALICE)
    STRSQL
ENDPGM
